DELIMITER $$

USE `apptrack`$$

CREATE FUNCTION split_string(

stringToSplit VARCHAR(256), SIGN VARCHAR(12), POSITION INT) RETURNS VARCHAR(256)
BEGIN
        RETURN REPLACE(SUBSTRING(SUBSTRING_INDEX(stringToSplit, SIGN, POSITION),LENGTH(SUBSTRING_INDEX(stringToSplit, SIGN, POSITION -1)) + 1), SIGN, '');
END
